### ISSUE TITLE
Got `System.MissingMethodException` if reference `Microsoft.Azure.Kusto.Ingest` greater or equal to "12.2.0"

### ISSUE THREAD

**Issue by wxxb789** [saguiitay/serilog-sinks-azuredataexplorer#34]
## details

```Exception
2024-07-22T06:13:54.8221835Z Exception while emitting periodic batch from Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink: System.MissingMethodException: Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'.
   at Serilog.Sinks.AzureDataExplorer.Sinks.AzureDataExplorerSink.CreateStreamFromLogEvents(IEnumerable`1 batch)
   at Serilog.Sinks.AzureDataExplorer.Sinks.AzureDataExplorerSink.EmitBatchAsync(IEnumerable`1 batch)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
```

## why reference `Microsoft.Azure.Kusto.Ingest` >= "12.2.0"

cause security issue, latest version fixed some vulnerabilities.

## reproduce

```c#
using System.Security.Cryptography.X509Certificates;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

using Serilog;
using Serilog.Debugging;
using Serilog.Events;
using Serilog.Sinks.AzureDataExplorer;
using Serilog.Sinks.AzureDataExplorer.Extensions;

Console.WriteLine("App Started.");

SelfLog.Enable(Console.Error);

var certificate = new X509Certificate2("<your cert path>"
    ?? throw new ArgumentException("File Path of X509Certificate2 Must Be Valid."));

// Debug Serilog and Adx connection
var factory = LoggerFactory.Create(builder =>
{
    // doc: https://github.com/Azure/serilog-sinks-azuredataexplorer/blob/main/src/Serilog.Sinks.AzureDataExplorer.Samples/Program.cs

    var logger = new LoggerConfiguration()
     .MinimumLevel.Debug()
     .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
     .Enrich.FromLogContext()
     .WriteTo.AzureDataExplorerSink(new AzureDataExplorerSinkOptions
     {
         IngestionEndpointUri = "<your endpoint>",
         DatabaseName = "<your database>",
         TableName = "your table name",
         FlushImmediately = true,
         Period = TimeSpan.FromSeconds(5),
         ColumnsMapping = new[]
         {
             new SinkColumnMapping { ColumnName = "Timestamp", ColumnType = "datetime", ValuePath = "$.Timestamp" },
             new SinkColumnMapping { ColumnName = "Level", ColumnType = "string", ValuePath = "$.Level" },
             new SinkColumnMapping { ColumnName = "Message", ColumnType = "string", ValuePath = "$.Message" },
             new SinkColumnMapping { ColumnName = "Exception", ColumnType = "string", ValuePath = "$.Error" },
             new SinkColumnMapping { ColumnName = "Properties", ColumnType = "dynamic", ValuePath = "$.Properties" },
             new SinkColumnMapping { ColumnName = "TraceId", ColumnType = "string", ValuePath = "$.Properties.TraceId" },
         },
     }.WithAadApplicationCertificate(
         "<your client id>",
         certificate,
         "<your tenant id>",
         sendX5C: true))
     .CreateLogger();
    builder.AddSerilog(logger, true);
});

using (factory)
{
    var logger = factory.CreateLogger<Program>();

    var now = DateTime.UtcNow;

    // test normal log
    logger.LogInformation("Adx&Serilog Debug, Test{NowTime}", now);
}

Console.WriteLine("Done");

```

**Comment by wxxb789** [comment]
Preliminary Analysis:
It seems that the latest `Microsoft.Azure.Kusto.Ingest` reference the `Microsoft.IO.RecyclableMemoryStream` >= "3.0.0" but `Serilog.Sinks.AzureDataExplorer` doesn't support it yet.

**Comment by ag-ramachandran** [comment]
Hi @wxxb789 , we are working on a upgrade of the connector. Will get a version out early next week

**Comment by tanmaya-panda1** [comment]
Hi @wxxb789 , we have released a new nuget version of serilog-sinks-azuredataexplorer. Can you please update to this version and check if the issue is still reproducible. Please do use 1.1.1 lib with 12.2.4 for kusto. Thanks!

**Comment by wxxb789** [comment]
everything looks good to me, thanks for your help.
